### ISSUE TITLE
Code Review - Devous

### ISSUE THREAD

**Issue by Devous** [Mqzn/mLib#2]
# Code Review
Not gunna lie, with a brief look over there doesn't seem to be much I can point out as wrong / bad practice - that I picked up on anyway. So I'll just list the few small things I found.

- Method name `onCLick` rather than `onClick` - See [here](https://github.com/Mqzn/mLib/blob/master/src/main/java/dev/mqzn/lib/menus/MenuSerializable.java#L21).
- You should consider making use of JetBrains `@NotNull` & `@Nullable` annotations for fields, methods and parameters to help with readability - and also needed / unneeded null checks.
- Use Bukkit's logger rather than `System.out.println`.
- In my opinion, using `String#format` is cleaner than what you're doing [here](https://github.com/Mqzn/mLib/blob/master/src/main/java/dev/mqzn/lib/menus/MenuPage.java#L110).
- I don't like the naming of `register` and `unregister`. It can be interpreted that they are for registering menus, but it may be confused as a method to register/unregister the manager itself? You could name them something like `registerMenu` to avoid confusion - See [here](https://github.com/Mqzn/mLib/blob/master/src/main/java/dev/mqzn/lib/menus/MenuManager.java#L42).
  - Also for consistency, as you've done so with your `MenuEntity#register/unregisterEntity` - See [here](https://github.com/Mqzn/mLib/blob/master/src/main/java/dev/mqzn/lib/menus/MenuEntity.java#L68).
- I'm actually unsure if this is good/bad practice, but more recently I've began liking the idea of your manager handling your listener - like it hands off the event. E.g. [here](https://github.com/Mqzn/mLib/blob/master/src/main/java/dev/mqzn/lib/menus/MenuListener.java#L12), instead of running the logic for the event inside your `onClick` method, I would have a method in the manager along the lines of `handleInventoryClick` and call `Manager#handleInventoryClick` inside your listener.
- Inconsistent use of access modifiers throughout project - See [here](https://github.com/Mqzn/mLib/blob/master/src/main/java/dev/mqzn/lib/menus/Menu.java#L19) for one example.
  - Some places you have written protected, others you haven't? Also I haven't looked at `inventory` properly but couldn't it be private anyway?
- You use `this` in many unneeded places, and also inconsistently. In my opinion you should only use `this` when you need to, it doesn't help readability, and just adds boilerplate.

All in all, I couldn't find many issues - all minor things. Your design principles in `menus` seem pretty good and consistent, I may of course have missed something; who knows. Good menu library though! :)

**Comment by Mqzn** [comment]
For the inconsistent use of access modifies, some functions i wanted them to be `Package private` and others i wanted them to be used only in sub classes `protected`

"You use this in many unneeded places, and also inconsistently. In my opinion you should only use this when you need to, it doesn't help readability, and just adds boilerplate."
Give me an example of using `this` in a useless way

**Comment by Devous** [comment]
> For the inconsistent use of access modifies, some functions i wanted them to be `Package private` and others i wanted them to be used only in sub classes `protected`
Okay this makes sense, went completely over my head; not sure why - my bad.
> "You use this in many unneeded places, and also inconsistently. In my opinion you should only use this when you need to, it doesn't help readability, and just adds boilerplate." Give me an example of using `this` in a useless way
- [here](https://github.com/Mqzn/mLib/blob/f6881b90599dd6069d83eaaef1f5766b4bafd5ae/src/main/java/dev/mqzn/lib/menus/Menu.java#L38)
- [here](https://github.com/Mqzn/mLib/blob/f6881b90599dd6069d83eaaef1f5766b4bafd5ae/src/main/java/dev/mqzn/lib/menus/Menu.java#L46)
- [here](https://github.com/Mqzn/mLib/blob/f6881b90599dd6069d83eaaef1f5766b4bafd5ae/src/main/java/dev/mqzn/lib/menus/Menu.java#L49)
- [here](https://github.com/Mqzn/mLib/blob/f6881b90599dd6069d83eaaef1f5766b4bafd5ae/src/main/java/dev/mqzn/lib/menus/Menu.java#L63)
- Etc, etc. You don't need to call `this` in these places. 
#
## The proper use case for `this`
A very professional article by [Devous](https://github.com/Devous).

Okay so you should only use `this` in three scenarios. 

### Scenario 1
Using `this` to disambiguate references to variables.
```java
public class Foo {
    private String name;

    public void setName(String name) {
        this.name = name;
    }
}
```
### Scenario 2
Using `this` to pass an instance to another object.
```java
public class Foo {
    public String useFunMethod() {
        Fun fun = new Fun();
        return fun.funMethod(this);
    }

    public String getName() {
        return "Foo";
    }
}

public class Fun
{
    public String funMethod(Foo obj) {
        return obj.getName();
    }
}
```
### Scenario 3
Using `this` to call alternate constructors.
```java
public class Foo {
    public Foo() {
        this("Alternate constructor");
    }

    public Foo(String s) {
        // Do stuff
    }
}
```

**Comment by Mqzn** [comment]
Ohhh, I thought you meant the use of `this` to cache the instance of a class in the constructor
nevermind.
As an answer, i use `this` to improve the readability for me when i read my  code
